# GitHub Actions workflow for Flutter CI/CD

name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install Flutter with a specific version
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6' # Use latest stable Flutter version
          channel: 'stable'
          cache: true

      # Ensure Dart is up to date
      - name: Install Dart
        run: |
          sudo apt-get update
          sudo apt-get install -y dart
          dart --version
          flutter doctor

      # Get dependencies
      - name: Install dependencies
        run: flutter pub get

      # Verify formatting (optional)
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      # Analyze project source
      - name: Analyze project source
        run: flutter analyze

      # Run Flutter tests
      - name: Run tests
        run: flutter test
